### ISSUE TITLE
MapMarkers Plugin does not implement the new event system

### ISSUE THREAD

**Issue by StefanBossbaly** [overviewer/Minecraft-Overviewer-Addons#15]
Trying to start Bukkit  1.2.5R1.0 with MapMarkers.jar causes an error since the old event system was deprecated and with that the `PlayerListener` class which MapMarker relied on. MapMarkers will have to use the new event system if it wants to support newer versions of Bukkit

**Comment by pironic** [comment]
Unfortunetly, I am going to close this ticket. Although we include the jar files with the addon, we do not have direct control over the source of the bukkit plugin. You'll need to get a hold of the bukkit plugin's creator to update it. The one we include is created by TJ09 and his repository is located at: http://tj09.net/minecraft/MapMarkers/

**Comment by FabianN** [comment]
Here is a version that should work, I haven't tested it with any 1.2.\* versions myself, but from the look of the info of the plugin it should work with 1.2.5R1

http://dev.bukkit.org/server-mods/mapmarkers/
